### PR TITLE
Add double precision option

### PR DESCRIPTION
**Pull request by ghost**
:)

### CODE REVIEW

**Comment by BareRose** [comment]
One small thing: I like to keep defines as short as possible while still being unambiguous, so `DVECTOR_DOUBLE` would be preferrable.

**Comment by ghost** [comment]
Done.

**Comment by ghost** [comment]
I was considering that `sinf` etc. [may not be necessary in C99](https://en.cppreference.com/w/c/numeric/math/sin), but there are a number of integer literals, which are treated as `double`s by `math.h` unless cast to something else. dvector does cast to `DVTYPE` in many places, but the logic is not completely clear to me. Any thoughts on this?

**Comment by BareRose** [comment]
> dvector does cast to DVTYPE in many places

It doesn't, not explicitly anyway. The way it's made is so that any integer literals are automatically promoted to `DVTYPE` according to C's type promotion rules. (Maybe C++ is different, you're more familiar with it than myself.)

Example (Lines 417-420):

```
VDEF quat quatAxisAngle (vec3 a, DVTYPE r) {
    DVTYPE s = DVSIN(r/2);
    return QUAT(a.x*s, a.y*s, a.z*s, DVCOS(r/2));
}
```

Both integer literals are of the form `r/2`, causing implicit conversion rules to result in promotion to `DVTYPE` because `r` is `DVTYPE`. As such, using the type-generic macro in place of `DVSIN` should work just fine.

The reason why I'd like to avoid type generic macros anyway is that they require the header `tgmath.h`, and having as few includes - even standard headers - is generally a good thing cause sadly not all C implementations fully comply to the standard (and dirty ones will just use `math.h`'s `sin` instead of the macro, thus causing double precision to be utilized unnecessarily).

**Comment by ghost** [comment]
Understood. Better to play it safe.

**Pull request merged**
